# Generated by Django 5.0.3 on 2024-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentralBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="MainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner1", models.URLField()),
                ("banner2", models.URLField()),
                ("banner3", models.URLField()),
                ("banner4", models.URLField()),
                ("banner5", models.URLField()),
            ],
        ),
    ]
