# Generated by Django 5.0.3 on 2024-08-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centralbanner",
            old_name="image_url",
            new_name="banner",
        ),
    ]
