# Generated by Django 5.0.3 on 2024-07-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="thumbnail",
            new_name="thumbnail_image",
        ),
    ]
