# Generated by Django 5.0.3 on 2024-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_rename_thumbnail_article_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
