# Generated by Django 5.0.3 on 2024-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ABOUT", "About"),
                            ("FASHION", "Fashion"),
                            ("FEATURE", "Feature"),
                            ("PHOTOGRAPHY", "Photography"),
                            ("FILM", "Film"),
                            ("ART", "Art"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("image_url", models.URLField()),
            ],
        ),
    ]
