# Generated by Django 5.0.3 on 2024-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_article1", models.URLField()),
                ("main_article2", models.URLField()),
                ("main_article1_redirect_url", models.URLField()),
                ("main_article2_redirect_url", models.URLField()),
            ],
        ),
    ]
