# Generated by Django 4.2.9 on 2024-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_oid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
