# Generated by Django 4.2.9 on 2024-02-03 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="directNumber",
            new_name="direct_number",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="oid",
            new_name="kakao_oid",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="profileImage",
            new_name="profile_image",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="test@naver.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
