# Generated by Django 5.0.3 on 2024-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("published_at", models.DateField()),
                ("publication_number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
